apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260616-155148-9t9nnpyl4y9u-service
spec:
  selector:
    app: enterprise-system-20260616-155148-9t9nnpyl4y9u
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
